live_config_reload = false

[env]
TERM = "xterm-256color"

# opacity = 0.8
# blur = true

[window]
padding.x = 4
padding.y = 4

startup_mode = "Maximized"

decorations = "Buttonless"

[font]
# normal.family = "JetBrainsMono Nerd Font"
# normal.family = "BlexMono Nerd Font"
# normal.family = "UbuntuMono Nerd Font"
normal.family = "Berkeley Mono Trial"
size = 20
# size = 22

[cursor]
style.shape = "Block"
# style.blinking = "Always"
# blink_interval = 500
# blink_timeout = 0

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true

[colors.primary]
background = '0x282c34'
foreground = '0xbbc2cf'

[colors.normal]
black = '0x282c34'
red = '0xff6c6b'
green = '0x98be65'
yellow = '0xecbe7b'
blue = '0x51afef'
magenta = '0xc678dd'
cyan = '0x46d9ff'
white = '0xbbc2cf'
