import = [
  "~/.config/alacritty/themes/themes/horizon-dark.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding.x = 4
padding.y = 4

startup_mode = "Maximized"

decorations = "Buttonless"

opacity = 0.8
blur = true


[font]
normal.family = "JetBrainsMono Nerd Font"
size = 20

[cursor]
style.shape = "Block"
style.blinking = "Always"
blink_interval = 500
blink_timeout = 0

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true
