general.import = [
  "~/.config/alacritty/gruber-darker.toml"
]

general.live_config_reload = false

[env]
TERM = "xterm-256color"

[window]
padding.x = 4
padding.y = 4

# opacity = 0.8
# blur = true

startup_mode = "Maximized"

decorations = "Buttonless"

[font]
# normal.family = "JetBrainsMono Nerd Font"
# normal.family = "BlexMono Nerd Font"
# normal.family = "CodeNewRoman Nerd Font"
normal.family = "Iosevka Nerd Font"
# size = 19
size = 21

[cursor]
style.shape = "Block"
# style.blinking = "Always"
# blink_interval = 500
# blink_timeout = 0

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true
