live_config_reload = false

[env]
TERM = "xterm-256color"

[window]
padding.x = 4
padding.y = 4

startup_mode = "Maximized"

decorations = "Buttonless"

[font]
# normal.family = "JetBrainsMono Nerd Font"
# normal.family = "FiraMono Nerd Font"
normal.family = "SauceCodePro Nerd Font"
size = 18

[cursor]
style.shape = "Block"
style.blinking = "Always"
blink_interval = 500
blink_timeout = 0

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true

[colors.primary]
background = '0x282828'
foreground = '0xd4be98'

[colors.normal]
black = '0x3c3836'
red = '0xea6962'
green = '0xa9b665'
yellow = '0xd8a657'
blue = '0x7daea3'
magenta = '0xd3869b'
cyan = '0x89b482'
white = '0xd4be98'
[colors.bright]
black = '0x3c3836'
red = '0xea6962'
green = '0xa9b665'
yellow = '0xd8a657'
blue = '0x7daea3'
magenta = '0xd3869b'
cyan = '0x89b482'
white = '0xd4be98'
