import = [
    "~/.config/alacritty/themes/themes/gruvbox_material_medium_dark.toml"
]

live_config_reload = false

[env]
TERM = "xterm-256color"

[window]
opacity = 0.8
blur = true

padding.x = 4
padding.y = 4

startup_mode = "Maximized"

decorations = "Buttonless"

[font]
# normal.family = "JetBrainsMono Nerd Font"
# normal.family = "BlexMono Nerd Font"
# normal.family = "UbuntuMono Nerd Font"
normal.family = "Berkeley Mono Trial"
#Fixed this font now :D
size = 20
# size = 22

[cursor]
style.shape = "Block"
# style.blinking = "Always"
# blink_interval = 500
# blink_timeout = 0

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true
