# general.import = [
#   "~/.config/alacritty/dracula.toml"
# ]

general.live_config_reload = false

[env]
TERM = "xterm-256color"

[window]
padding.x = 4
padding.y = 4

# opacity = 0.8
# blur = true

startup_mode = "Maximized"

decorations = "Buttonless"

[font]
# normal.family = "JetBrainsMono Nerd Font"
normal.family = "BlexMono Nerd Font"
# normal.family = "UbuntuMono Nerd Font"
# normal.family = "Berkeley Mono Trial"
size = 18
# size = 23

[cursor]
style.shape = "Block"
# style.blinking = "Always"
# blink_interval = 500
# blink_timeout = 0

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true


[colors.primary]
background = "0x2c2e34"
foreground = "0xe2e2e3"

[colors.normal]
black = "0x181819"
red = "0xfc5d7c"
green = "0x9ed072"
yellow = "0xe7c664"
blue = "0x76cce0"
magenta = "0xb39df3"
cyan = "0xf39660"
white = "0xe2e2e3"

[colors.bright]
black = "0x7f8490"
red = "0xfc5d7c"
green = "0x9ed072"
yellow = "0xe7c664"
blue = "0x76cce0"
magenta = "0xb39df3"
cyan = "0xf39660"
white = "0xe2e2e3"
