live_config_reload = false

[env]
TERM = "xterm-256color"

[window]
padding.x = 4
padding.y = 4

startup_mode = "Maximized"

decorations = "Buttonless"

[font]
# normal.family = "JetBrainsMono Nerd Font"
normal.family = "BlexMono Nerd Font"
# normal.family = "FiraMono Nerd Font"
size = 19

[cursor]
style.shape = "Block"
# style.blinking = "Always"
# blink_interval = 500
# blink_timeout = 0

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true

[colors.primary]
background = '0x1d2021'
foreground = '0xd5c4a1'

[colors.normal]
black=   '0x1d2021'
red=     '0xfb4934'
green=   '0xb8bb26'
yellow=  '0xfabd2f'
blue=    '0x83a598'
magenta= '0xd3869b'
cyan=    '0x8ec07c'
white=   '0xd5c4a1'

[colors.bright]
black=   '0x665c54'
red=     '0xfb4934'
green=   '0xb8bb26'
yellow=  '0xfabd2f'
blue=    '0x83a598'
magenta= '0xd3869b'
cyan=    '0x8ec07c'
white=   '0xfbf1c7'

[colors.cursor]
text = "#000000"
cursor = "#FFFFFF"
